# Install a specified list of sets and packages.
---
- name: Install package set {{ package_sets }}
  ansible.builtin.command:
    cmd: emerge --noreplace "@{{ item }}"
  with_items: "{{ package_sets }}"
  tags:
    - set

- name: Install additional packages
  ansible.builtin.command:
    cmd: emerge "{{ item }}"
  with_items: "{{ prefix_packages }}"
  when: prefix_packages is iterable
